import SharedCore

public typealias BridgeProtocol = SharedCore.BridgeProtocol
public typealias AMuleConnectionConfig = SharedCore.AMuleConnectionConfig
public typealias SerializedBridgeAdapter = SharedCore.SerializedBridgeAdapter
public typealias BridgeCapabilitiesPayload = SharedCore.BridgeCapabilitiesPayload
public typealias BridgeStatusPayload = SharedCore.BridgeStatusPayload
public typealias BridgeDownloadPayload = SharedCore.BridgeDownloadPayload
public typealias BridgeSearchPayload = SharedCore.BridgeSearchPayload
public typealias BridgeConnectionPrefsPayload = SharedCore.BridgeConnectionPrefsPayload
public typealias BridgeServerPayload = SharedCore.BridgeServerPayload
public typealias BridgeUploadPayload = SharedCore.BridgeUploadPayload
public typealias BridgeSharedFilePayload = SharedCore.BridgeSharedFilePayload
public typealias BridgeCoreLogPayload = SharedCore.BridgeCoreLogPayload
public typealias BridgeCategoryPayload = SharedCore.BridgeCategoryPayload
public typealias BridgeFriendPayload = SharedCore.BridgeFriendPayload
public typealias BridgeStatsTreeNodePayload = SharedCore.BridgeStatsTreeNodePayload
public typealias BridgeStatsGraphsPayload = SharedCore.BridgeStatsGraphsPayload
public typealias DownloadSourceItem = SharedCore.DownloadSourceItem
public typealias AMuleClientError = SharedCore.AMuleClientError
public typealias BridgeCapabilityGate = SharedCore.BridgeCapabilityGate
public typealias StatusSnapshot = SharedCore.StatusSnapshot
public typealias AMuleFormatter = SharedCore.AMuleFormatter
